let agentes = [
    {nome: "Jett",
        papel: "Duelista",
        descricao: "Agente ágil e evasiva, conhecida por suas habilidades de mobilidade e suas facas letais.",
        habilidades: ["Cloudburst", "Updraft", "Tailwind", "Blade Storm"],
        link: "https://valorant.fandom.com/wiki/Jett",
        tags: "vento",
    },
    {
        nome: "Phoenix",
        papel: "Duelista",
        descricao: "Duelista que utiliza suas habilidades de fogo para criar oportunidades e confundir os inimigos.",
        habilidades: ["Curveball", "Hot Hands", "Blaze", "Run it Back"],
        link: "https://valorant.fandom.com/wiki/Phoenix",
        tags: "fogo",
    },
    {
        nome: "Sage",
        papel: "Sentinela",
        descricao: "Sentinela curandeira, que utiliza suas habilidades de cura e barreiras para proteger seus aliados.",
        habilidades: ["Slow Orb", "Barrier Orb", "Healing Orb", "Resurrection"],
        link: "https://valorant.fandom.com/wiki/Sage",
        tags: "cura",
    },
    {
        nome: "Reyna",
        papel: "Duelista",
        descricao: "Duelista que se alimenta da morte, se fortalecendo a cada abate.",
        habilidades: ["Leer", "Devour", "Dismiss", "Empress"],
        link: "https://valorant.fandom.com/wiki/Reyna",
        tags: "roxa",
    },
    {
        nome: "Brimstone",
        papel: "Controlador",
        descricao: "Controlador que domina o campo de batalha de cima, utilizando habilidades de fogo para criar oportunidades táticas.",
        habilidades: ["Stim Beacon", "Incendiary", "Sky Smoke", "Orbital Strike"],
        link: "https://valorant.fandom.com/wiki/Brimstone",
        tags: "barbudo",
    },
    {
        nome: "Viper",
        papel: "Controlador",
        descricao: "Controladora que utiliza habilidades de gás venenoso para isolar áreas e prejudicar os inimigos.",
        habilidades: ["Snake Bite", "Poison Cloud", "Toxic Screen", "Viper's Pit"],
        link: "https://valorant.fandom.com/wiki/Viper",
        tags: "veneno",
    },
    {
        nome: "Breach",
        papel: "Iniciador",
        descricao: "Iniciador que quebra as defesas inimigas, utilizando habilidades de choque para abrir caminho para sua equipe.",
        habilidades: ["Aftershock", "Flashpoint", "Fault Line", "Rolling Thunder"],
        link: "https://valorant.fandom.com/wiki/Breach",
        tags: "bang",
    },
    {
        nome: "Raze",
        papel: "Duelista",
        descricao: "Duelista explosiva, que utiliza suas habilidades explosivas para eliminar os inimigos e causar caos no campo de batalha.",
        habilidades: ["Blast Pack", "Paint Shells", "Boom Bot", "Showstopper"],
        link: "https://valorant.fandom.com/wiki/Raze",
        tags: "baiana",
    },
    {
        nome: "Skye",
        papel: "Iniciadora",
        descricao: "Iniciadora que utiliza animais para explorar e localizar os inimigos.",
        habilidades: ["Seekers", "Trailblazer", "Guiding Light", "Regroup"],
        link: "https://valorant.fandom.com/wiki/Skye",
        tags: "animal reconhecimento",
      },
      {
        nome: "Killjoy",
        papel: "Sentinela",
        descricao: "Sentinela que utiliza dispositivos para proteger áreas específicas do mapa.",
        habilidades: ["Alarmbot", "Turret", "Nanoswarm", "Lockdown"],
        link: "https://valorant.fandom.com/wiki/Killjoy",
        tags: "armadilha defesa",
      },
      {
        nome: "Omen",
        papel: "Controlador",
        descricao: "Controlador que utiliza sombras para teletransportar-se e confundir os inimigos.",
        habilidades: ["Paranoia", "Shrouded Step", "Dark Cover", "From the Shadows"],
        link: "https://valorant.fandom.com/wiki/Omen",
        tags: "sombra teleporte",
      },
      {
        nome: "Cypher",
        papel: "Sentinela",
        descricao: "Sentinela que utiliza dispositivos de vigilância para monitorar o mapa e localizar os inimigos.",
        habilidades: ["Trapwire", "Cyber Cage", "Spycam", "Neural Theft"],
        link: "https://valorant.fandom.com/wiki/Cypher",
        tags: "vigilância informação",
      },
      {
        nome: "Neon",
        papel: "Duelista",
        descricao: "Duelista elétrica que utiliza sua velocidade e habilidades de choque para desorientar os inimigos.",
        habilidades: ["Relay Bolt", "High Gear", "Overdrive", "Eruption"],
        link: "https://valorant.fandom.com/wiki/Neon",
        tags: "velocidade eletricidade",
      },
      {
        nome: "Chamber",
        papel: "Sentinela",
        descricao: "Sentinela que utiliza armas e armadilhas para controlar o campo de batalha.",
        habilidades: ["Headhunter", "Trademark", "Rendezvous", "Tour de Force"],
        link: "https://valorant.fandom.com/wiki/Chamber",
        tags: "arma sentinela",
      },
      {
        nome: "KAY/O",
        papel: "Iniciador",
        descricao: "Iniciador robótico que utiliza suas habilidades para suprimir e desativar os inimigos.",
        habilidades: ["FRAG/ment", "ZERO/point", "FLASH/drive", "NULL/cmd"],
        link: "https://valorant.fandom.com/wiki/KAY/O",
        tags: "robô supressão",
      },
      {
        nome: "Astra",
        papel: "Controladora",
        descricao: "Controladora cósmica que utiliza estrelas para controlar o campo de batalha.",
        habilidades: ["Starlight", "Nova Pulse", "Nebula", "Cosmic Divide"],
        link: "https://valorant.fandom.com/wiki/Astra",
        tags: "estrela cósmica",
      },
      {
        nome: "Yoru",
        papel: "Duelista",
        descricao: "Duelista que utiliza habilidades de teletransporte e distração para confundir os inimigos.",
        habilidades: ["Gatecrash", "Fakeout", "Dimensional Drift", "Blindside"],
        link: "https://valorant.fandom.com/wiki/Yoru",
        tags: "teleporte enganação",
      },
      {
        nome: "Iso",
        papel: "Duelista",
        descricao: "Duelista que utiliza ondas de choque para controlar o campo de batalha e eliminar inimigos.",
        habilidades: ["Eko", "Pulse", "Flashdrive", "Kingmaker"],
        link: "https://valorant.fandom.com/wiki/Iso",
        tags: "som onda choque"
      },
      {
        nome: "Deadlock",
        papel: "Sentinela",
        descricao: "Sentinela que utiliza armadilhas e tecnologia avançada para controlar o campo de batalha.",
        habilidades: ["Annihilation", "Sonar", "Barbed Wire", "Cosmic Divide"],
        link: "https://valorant.fandom.com/wiki/Deadlock",
        tags: "armadilha tecnologia"
      },
      {
        nome: "Gekko",
        papel: "Iniciador",
        descricao: "Iniciador que utiliza criaturas bioluminiscentes para explorar e atacar os inimigos.",
        habilidades: ["Wingman", "Moshpit", "Thrash", "Shields"],
        link: "https://valorant.fandom.com/wiki/Gekko",
        tags: "criaturas exploração"
      },
      {
        nome: "Harbor",
        papel: "Controlador",
        descricao: "Controlador que manipula água para criar barreiras e inundar áreas do mapa.",
        habilidades: ["High Tide", "Cove", "Cascade", "Reckoning"],
        link: "https://valorant.fandom.com/wiki/Harbor",
        tags: "água controle"
      },
      {
        nome: "Fade",
        papel: "Iniciadora",
        descricao: "Iniciadora que utiliza pesadelos para localizar e assustar os inimigos.",
        habilidades: ["Prowler", "Haunt", "Seize", "Nightfall"],
        link: "https://valorant.fandom.com/wiki/Fade",
        tags: "pesadelo medo"
      },
      {
        nome: "Vyse",
        papel: "Controladora",
        descricao: "Vyse controla o campo de batalha com suas habilidades de manipulação de tempo, criando zonas de lentidão e explosões temporais.",
        habilidades: ["Chronostasis", "Temporal Surge", "Time Bomb", "Grand Finale"],
        link: "https://valorant.fandom.com/wiki/Vyse",
        tags: "tempo controle"
      },
      {
        nome: "Clove",
        papel: "Duelista",
        descricao: "Clove utiliza suas garras e habilidades acrobáticas para eliminar inimigos à curta distância.",
        habilidades: ["Pounce", "Slash", "Tiger's Stance", "Feral"],
        link: "https://valorant.fandom.com/wiki/Clove",
        tags: "agilidade melee"
      }
];
